#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
<<<<<<< Updated upstream
# Generated by Vivado on Thu Mar 23 22:01:16 CET 2023
=======
# Generated by Vivado on Tue Apr 25 16:42:26 CEST 2023
>>>>>>> Stashed changes
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
<<<<<<< Updated upstream
ExecStep xelab -wto 0afd0da3bb0341ddad0a1cad00bd95d6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot IDC_tb_behav xil_defaultlib.IDC_tb -log elaborate.log
=======
ExecStep xelab -wto 0afd0da3bb0341ddad0a1cad00bd95d6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot MicroprogramController_tb_behav xil_defaultlib.MicroprogramController_tb -log elaborate.log
>>>>>>> Stashed changes
