#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
<<<<<<< Updated upstream
# Generated by Vivado on Thu Mar 23 22:01:18 CET 2023
=======
# Generated by Vivado on Tue Apr 25 16:42:29 CEST 2023
>>>>>>> Stashed changes
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
<<<<<<< Updated upstream
ExecStep xsim IDC_tb_behav -key {Behavioral:sim_1:Functional:IDC_tb} -tclbatch IDC_tb.tcl -view /zhome/ad/e/169133/VHDL_PW_project/PWA/xillinxProjects/RF/IDC_tb_behav.wcfg -log simulate.log
=======
ExecStep xsim MicroprogramController_tb_behav -key {Behavioral:sim_1:Functional:MicroprogramController_tb} -tclbatch MicroprogramController_tb.tcl -view /zhome/ad/e/169133/VHDL_PW_project/PWA/xillinxProjects/RF/MicroprogramController_tb_behav.wcfg -log simulate.log
>>>>>>> Stashed changes
