#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
<<<<<<< Updated upstream
<<<<<<< Updated upstream
# Generated by Vivado on Thu Mar 16 11:15:59 CET 2023
=======
# Generated by Vivado on Thu Mar 30 12:08:48 CEST 2023
>>>>>>> Stashed changes
=======
# Generated by Vivado on Thu Apr 27 10:43:00 CEST 2023
>>>>>>> Stashed changes
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
<<<<<<< Updated upstream
<<<<<<< Updated upstream
ExecStep xsim ProgramCounter_tb_behav -key {Behavioral:sim_1:Functional:ProgramCounter_tb} -tclbatch ProgramCounter_tb.tcl -view /zhome/4a/d/162008/project1/PWA/xillinxProjects/RF/Datapath_tb_behav.wcfg -log simulate.log
=======
ExecStep xsim Ram256X16_tb_behav -key {Behavioral:sim_1:Functional:Ram256X16_tb} -tclbatch Ram256X16_tb.tcl -view /zhome/4a/d/162008/project1/PWA/xillinxProjects/RF/Datapath_tb_behav.wcfg -log simulate.log
>>>>>>> Stashed changes
=======
ExecStep xsim Decoder4x16_tb_behav -key {Behavioral:sim_1:Functional:Decoder4x16_tb} -tclbatch Decoder4x16_tb.tcl -view /zhome/4a/d/162008/project1/PWA/xillinxProjects/RF/Datapath_tb_behav.wcfg -log simulate.log
>>>>>>> Stashed changes
