#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
<<<<<<< Updated upstream
# Generated by Vivado on Thu Mar 16 10:17:16 CET 2023
=======
# Generated by Vivado on Thu Apr 27 10:08:42 CEST 2023
>>>>>>> Stashed changes
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim Decoder4x16_tb_behav -key {Behavioral:sim_1:Functional:Decoder4x16_tb} -tclbatch Decoder4x16_tb.tcl -view /zhome/39/2/168854/PWA/xillinxProjects/RF/Datapath_tb_behav.wcfg -log simulate.log
