webtalk_init -webtalk_dir /zhome/4a/d/162008/project1/PWA/xillinxProjects/RF/test.sim/sim_1/behav/xsim/xsim.dir/logic_unit8bit_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Mar  2 17:57:41 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "176339219_1777488102_210753852_502" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3ad791f5-53b2-4940-b0d1-11aa2815ac84" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0afd0da3bb0341ddad0a1cad00bd95d6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Scientific" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Scientific Linux release 7.9 (Nitrogen)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2599.853 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "270.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "140 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "126164_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2194989500 -regid "176339219_1777488102_210753852_502" -xml /zhome/4a/d/162008/project1/PWA/xillinxProjects/RF/test.sim/sim_1/behav/xsim/xsim.dir/logic_unit8bit_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /zhome/4a/d/162008/project1/PWA/xillinxProjects/RF/test.sim/sim_1/behav/xsim/xsim.dir/logic_unit8bit_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /zhome/4a/d/162008/project1/PWA/xillinxProjects/RF/test.sim/sim_1/behav/xsim/xsim.dir/logic_unit8bit_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
